CREATE TABLE IF NOT EXISTS users
(
    "user_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name"    VARCHAR(255)                                        NOT NULL,
    "email"   VARCHAR(255) UNIQUE                                 NOT NULL
);

CREATE TABLE IF NOT EXISTS items
(
    "item_id"      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "name"         VARCHAR(255)                                        NOT NULL,
    "description"  VARCHAR(100)                                        NOT NULL,
    "is_available" BOOLEAN                                         DEFAULT TRUE,
    "owner_id"     BIGINT                                                      ,
    "request_id"   BIGINT
);

CREATE TABLE IF NOT EXISTS bookings
(
    "booking_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "start_date"    TIMESTAMP                                        NOT NULL,
    "end_date"      TIMESTAMP                                        NOT NULL,
    "item_id"       BIGINT                                                   ,
    "booker_id"     BIGINT                                                   ,
    "status"        VARCHAR
);

CREATE TABLE IF NOT EXISTS comments
(
    "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "text"       VARCHAR(1000)                                       NOT NULL,
    "item_id"    BIGINT                                                      ,
    "author_id"  BIGINT                                                      ,
    "created"    TIMESTAMP                                           NOT NULL
);

CREATE TABLE IF NOT EXISTS requests
(
    "request_id"   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "description"  VARCHAR(1000)                                       NOT NULL,
    "requester_id" BIGINT                                                      ,
    "created"      TIMESTAMP                                           NOT NULL
);